"""
Utilities Package for Competitor Analyzer Service

This package contains utility functions for competitor analysis,
market analysis, content gap analysis, SEO analysis, and data transformation.
"""

# Import all utility functions from submodules
from .competitor_utils import (
    validate_competitor_url,
    normalize_competitor_urls,
    extract_domain_from_url,
    categorize_competitor_size,
    determine_competitor_type,
    calculate_competition_score,
    assess_domain_authority_tier,
    assess_page_speed_tier,
    assess_content_quality_tier,
    extract_competitor_insights,
    create_competitor_profile,
    create_competitor_metrics,
    validate_competitor_data,
    merge_competitor_analyses,
    create_fallback_competitor_analysis,
    batch_process_urls,
    calculate_similarity_score,
    filter_competitors_by_criteria,
)

from .market_utils import (
    calculate_market_share,
    determine_market_position,
    assess_competitive_intensity,
    calculate_market_concentration,
    identify_market_leaders,
    analyze_market_segments,
    identify_market_opportunities,
    analyze_market_trends,
    create_market_positioning,
    create_competitive_landscape,
    calculate_growth_potential,
    validate_market_data,
    create_market_benchmark,
)

from .content_gap_utils import (
    analyze_topic_distribution,
    analyze_content_depth,
    calculate_content_depth_score,
    analyze_content_formats,
    calculate_format_effectiveness,
    analyze_content_quality,
    identify_missing_topics,
    categorize_topic,
    identify_format_gaps,
    determine_format_complexity,
    estimate_format_engagement,
    get_format_distribution_channels,
    get_format_repurposing_potential,
    get_format_competitive_advantage,
    estimate_format_implementation_time,
    get_format_resource_requirements,
    calculate_gap_priority,
    validate_content_gap_data,
)

from .seo_utils import (
    analyze_seo_metrics,
    calculate_seo_score,
    analyze_keyword_gaps,
    estimate_search_volume,
    estimate_keyword_difficulty,
    determine_search_intent,
    calculate_keyword_gap_opportunity,
    estimate_keyword_traffic_potential,
    estimate_content_difficulty,
    determine_keyword_competition_level,
    estimate_keyword_trend,
    estimate_seasonal_pattern,
    get_related_keywords,
    generate_keyword_content_suggestions,
    calculate_keyword_priority,
    analyze_technical_seo_gaps,
    get_technical_requirements,
    get_seo_tools_for_gap,
    get_expected_improvement,
    get_implementation_steps,
    get_monitoring_metrics,
    validate_seo_data,
)

from .data_transformers import (
    transform_legacy_competitor_data,
    transform_engagement_metrics,
    transform_seo_metrics,
    transform_content_analysis,
    transform_market_data,
    transform_market_positioning,
    transform_to_api_response,
    transform_analysis_summary,
    identify_market_leaders,
    transform_content_gaps_to_analysis,
    transform_seo_gaps_to_analysis,
    transform_health_check_results,
    validate_analysis_results,
    transform_to_export_format,
    merge_analysis_results,
    filter_analysis_by_criteria,
)

# Export all utility functions for easy import
__all__ = [
    # Competitor Utils
    "validate_competitor_url",
    "normalize_competitor_urls",
    "extract_domain_from_url",
    "categorize_competitor_size",
    "determine_competitor_type",
    "calculate_competition_score",
    "assess_domain_authority_tier",
    "assess_page_speed_tier",
    "assess_content_quality_tier",
    "extract_competitor_insights",
    "create_competitor_profile",
    "create_competitor_metrics",
    "validate_competitor_data",
    "merge_competitor_analyses",
    "create_fallback_competitor_analysis",
    "batch_process_urls",
    "calculate_similarity_score",
    "filter_competitors_by_criteria",
    
    # Market Utils
    "calculate_market_share",
    "determine_market_position",
    "assess_competitive_intensity",
    "calculate_market_concentration",
    "identify_market_leaders",
    "analyze_market_segments",
    "identify_market_opportunities",
    "analyze_market_trends",
    "create_market_positioning",
    "create_competitive_landscape",
    "calculate_growth_potential",
    "validate_market_data",
    "create_market_benchmark",
    
    # Content Gap Utils
    "analyze_topic_distribution",
    "analyze_content_depth",
    "calculate_content_depth_score",
    "analyze_content_formats",
    "calculate_format_effectiveness",
    "analyze_content_quality",
    "identify_missing_topics",
    "categorize_topic",
    "identify_format_gaps",
    "determine_format_complexity",
    "estimate_format_engagement",
    "get_format_distribution_channels",
    "get_format_repurposing_potential",
    "get_format_competitive_advantage",
    "estimate_format_implementation_time",
    "get_format_resource_requirements",
    "calculate_gap_priority",
    "validate_content_gap_data",
    
    # SEO Utils
    "analyze_seo_metrics",
    "calculate_seo_score",
    "analyze_keyword_gaps",
    "estimate_search_volume",
    "estimate_keyword_difficulty",
    "determine_search_intent",
    "calculate_keyword_gap_opportunity",
    "estimate_keyword_traffic_potential",
    "estimate_content_difficulty",
    "determine_keyword_competition_level",
    "estimate_keyword_trend",
    "estimate_seasonal_pattern",
    "get_related_keywords",
    "generate_keyword_content_suggestions",
    "calculate_keyword_priority",
    "analyze_technical_seo_gaps",
    "get_technical_requirements",
    "get_seo_tools_for_gap",
    "get_expected_improvement",
    "get_implementation_steps",
    "get_monitoring_metrics",
    "validate_seo_data",
    
    # Data Transformers
    "transform_legacy_competitor_data",
    "transform_engagement_metrics",
    "transform_seo_metrics",
    "transform_content_analysis",
    "transform_market_data",
    "transform_market_positioning",
    "transform_to_api_response",
    "transform_analysis_summary",
    "identify_market_leaders",
    "transform_content_gaps_to_analysis",
    "transform_seo_gaps_to_analysis",
    "transform_health_check_results",
    "validate_analysis_results",
    "transform_to_export_format",
    "merge_analysis_results",
    "filter_analysis_by_criteria",
]

# Version information
__version__ = "1.0.0"
__description__ = "Utility functions for competitor analyzer service"
