"""
Keyword Researcher Constants

Constants and thresholds used across keyword researcher services.
"""

# Scoring thresholds
MIN_OPPORTUNITY_SCORE = 50.0
MAX_DIFFICULTY_SCORE = 70.0
MIN_SEARCH_VOLUME = 100
HIGH_VOLUME_THRESHOLD = 5000
LOW_COMPETITION_THRESHOLD = 30
HIGH_COMPETITION_THRESHOLD = 70

# Content analysis thresholds
OPTIMAL_META_DESCRIPTION_LENGTH = 155
OPTIMAL_TITLE_LENGTH = 60
MIN_KEYWORD_LENGTH = 3
MAX_KEYWORD_LENGTH = 100
KEYWORD_DENSITY_TARGET = 0.02

# Confidence thresholds
MIN_CONFIDENCE_SCORE = 0.7
HIGH_CONFIDENCE_SCORE = 0.9
DEFAULT_CONFIDENCE_SCORE = 0.8

# Analysis limits
MAX_SEED_KEYWORDS = 50
MAX_EXPANDED_KEYWORDS = 1000
MAX_RECOMMENDATIONS = 10
MAX_TOPIC_CLUSTERS = 20
MAX_CONTENT_SUGGESTIONS = 50

# Processing timeouts
AI_REQUEST_TIMEOUT = 30
ANALYSIS_TIMEOUT = 120
EXPANSION_TIMEOUT = 60

# Volume and traffic estimates
DEFAULT_SEARCH_VOLUME_BASE = 1000
SEARCH_VOLUME_RANGE = 5000
TRAFFIC_MULTIPLIER_LOW = 0.1
TRAFFIC_MULTIPLIER_HIGH = 0.3

# Content creation estimates
WORD_COUNT_MIN = 300
WORD_COUNT_MAX = 3000
WORD_COUNT_TARGET = 1500

# Seasonal factors
SEASONAL_FACTOR_MIN = 0.5
SEASONAL_FACTOR_MAX = 2.0
DEFAULT_SEASONAL_FACTOR = 1.0

# CPC estimates
DEFAULT_CPC = 2.5
MIN_CPC = 0.1
MAX_CPC = 50.0

# Difficulty scoring
DIFFICULTY_MIN = 0
DIFFICULTY_MAX = 100
DEFAULT_DIFFICULTY = 50

# Opportunity scoring
OPPORTUNITY_SCORE_MIN = 0
OPPORTUNITY_SCORE_MAX = 100
HIGH_OPPORTUNITY_THRESHOLD = 75
MEDIUM_OPPORTUNITY_THRESHOLD = 50

# Intent analysis confidence
INTENT_CONFIDENCE_HIGH = 0.9
INTENT_CONFIDENCE_MEDIUM = 0.7
INTENT_CONFIDENCE_LOW = 0.5

# Content format priorities
PRIORITY_HIGH = "high"
PRIORITY_MEDIUM = "medium"
PRIORITY_LOW = "low"

# Implementation time estimates
IMPLEMENTATION_TIME_QUICK = "1-2 weeks"
IMPLEMENTATION_TIME_MEDIUM = "3-4 weeks"
IMPLEMENTATION_TIME_LONG = "1-2 months"

# Success probability thresholds
SUCCESS_PROBABILITY_HIGH = 80
SUCCESS_PROBABILITY_MEDIUM = 60
SUCCESS_PROBABILITY_LOW = 40

# Conversion potential
CONVERSION_POTENTIAL_HIGH = 80
CONVERSION_POTENTIAL_MEDIUM = 60
CONVERSION_POTENTIAL_LOW = 40

# Content difficulty levels
DIFFICULTY_VERY_EASY = "very_easy"
DIFFICULTY_EASY = "easy"
DIFFICULTY_MEDIUM = "medium"
DIFFICULTY_HARD = "hard"
DIFFICULTY_VERY_HARD = "very_hard"

# Analysis depth levels
ANALYSIS_DEPTH_BASIC = "basic"
ANALYSIS_DEPTH_STANDARD = "standard"
ANALYSIS_DEPTH_COMPREHENSIVE = "comprehensive"

# Service health check
HEALTH_CHECK_TIMEOUT = 10
HEALTH_CHECK_PASSED = 3
HEALTH_CHECK_TOTAL = 3

# Default values for fallback responses
DEFAULT_TREND_DIRECTION = "stable"
DEFAULT_COMPETITION = "medium"
DEFAULT_INTENT = "informational"
DEFAULT_PRIORITY = "medium"

# Hash-based calculation ranges for simulated data
HASH_VOLUME_RANGE = 5000
HASH_DIFFICULTY_RANGE = 100
HASH_RELEVANCE_RANGE = 20
HASH_BASE_VOLUME = 1000
HASH_BASE_RELEVANCE = 0.8
