/**
 * Material-UI Tree Shaking Optimization
 * Reduces bundle size by importing only needed components
 */

// Tree-shaked imports - SAME FUNCTIONALITY, smaller bundles
export { 
  // Core components - import individually
  Core: {
    Box,
    CircularProgress,
    Typography,
    Container,
    Grid,
    Paper,
    Button,
    TextField,
    Card,
    CardContent,
    AppBar,
    Toolbar,
    Drawer,
    List,
    ListItem,
    ListItemText,
    Divider,
    IconButton,
    Menu,
    MenuItem,
    Dialog,
    DialogTitle,
    DialogContent,
    DialogActions,
    Snackbar,
    Alert,
    AlertTitle,
    Chip,
    Avatar,
    LinearProgress,
    Table,
    TableBody,
    TableCell,
    TableContainer,
    TableHead,
    TableRow,
    Pagination,
    Tabs,
    Tab,
    Switch,
    FormControl,
    FormControlLabel,
    Select,
    MenuItem as SelectMenuItem,
    InputLabel,
    Checkbox,
    RadioGroup,
    FormControlLabel as RadioLabel,
    Radio,
    Slider,
    Accordion,
    AccordionSummary,
    AccordionDetails,
    Breadcrumbs,
    Link,
    Tooltip,
    Fab,
    SpeedDial,
    SpeedDialAction,
    Backdrop,
    Modal,
  },
} from '@mui/material';

// Icons - import only what's used
export {
  // Navigation icons
  Dashboard,
  Home,
  Settings,
  Search,
  Add,
  Edit,
  Delete,
  Save,
  Cancel,
  Close,
  Menu as MenuIcon,
  ChevronLeft,
  ChevronRight,
  ExpandMore,
  // Action icons
  PlayArrow,
  Pause,
  Stop,
  Refresh,
  Download,
  Upload,
  Share,
  Visibility,
  VisibilityOff,
  // Status icons
  CheckCircle,
  Error as ErrorIcon,
  Warning as WarningIcon,
  Info as InfoIcon,
  Help,
  Lightbulb,
  TrendingUp,
  TrendingDown,
} from '@mui/icons-material';

// Re-exports for backward compatibility
export const MUI = {
  Core: {
    Box,
    CircularProgress,
    Typography,
    Container,
    Grid,
    Paper,
  },
  Layout: {
    AppBar,
    Toolbar,
    Drawer,
    List,
    ListItem,
    ListItemText,
    Divider,
  },
  Navigation: {
    Button,
    IconButton,
    Menu,
    MenuItem,
    Breadcrumbs,
    Link,
    Tooltip,
  },
  Feedback: {
    Dialog,
    DialogTitle,
    DialogContent,
    DialogActions,
    Snackbar,
    Alert,
    AlertTitle,
    Chip,
    Avatar,
  },
  Data: {
    Table,
    TableBody,
    TableCell,
    TableContainer,
    TableHead,
    TableRow,
    Pagination,
    LinearProgress,
  },
  Forms: {
    TextField,
    FormControl,
    FormControlLabel,
    Select,
    InputLabel,
    Checkbox,
    RadioGroup,
    RadioLabel,
    Radio,
    Slider,
    Switch,
  },
  Interactive: {
    Tabs,
    Tab,
    Accordion,
    AccordionSummary,
    AccordionDetails,
    Fab,
    SpeedDial,
    SpeedDialAction,
    Modal,
  },
  Icons: {
    Dashboard,
    Home,
    Settings,
    Search,
    Add,
    Edit,
    Delete,
    Save,
    Cancel,
    Close,
    MenuIcon,
    ChevronLeft,
    ChevronRight,
    ExpandMore,
    PlayArrow,
    Pause,
    Stop,
    Refresh,
    Download,
    Upload,
    Share,
    Visibility,
    VisibilityOff,
    CheckCircle,
    ErrorIcon,
    WarningIcon,
    InfoIcon,
    Help,
    Lightbulb,
    TrendingUp,
    TrendingDown,
  }
};
